In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [3]:
# Skip first row if it contains text
df = pd.read_excel("/content/glass.xlsx", header=1)

df.head()

                                   Data Description:
0                              RI : refractive index
1  Na: Sodium (unit measurement: weight percent i...
2                                      Mg: Magnesium
3                                       AI: Aluminum
4                                        Si: Silicon

In [4]:

df.columns = df.columns.str.strip()
df.columns

Index(['Data Description:'], dtype='object')

In [5]:
for col in df.columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Data Description:  0 non-null      float64
dtypes: float64(1)
memory usage: 276.0 bytes

In [6]:
df = df.dropna(how='all')
df = df.fillna(df.mean(numeric_only=True))

df.isna().sum()

Data Description:    0
dtype: int64

In [7]:
# Last column is usually glass type
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (0, 0)
Target shape: (0,)

In [8]:
print(df.columns)

Index(['Data Description:'], dtype='object')

In [9]:
target_col = df.columns[-1]

X = df.drop(columns=[target_col])
y = df[target_col]

print("X shape:", X.shape)
print("y unique values:", y.unique())

X shape: (0, 0)
y unique values: []

In [10]:

df = pd.read_excel("glass.xlsx", header=1)

df.columns = df.columns.str.strip()

df.head()

                                   Data Description:
0                              RI : refractive index
1  Na: Sodium (unit measurement: weight percent i...
2                                      Mg: Magnesium
3                                       AI: Aluminum
4                                        Si: Silicon

In [11]:
print("Shape before conversion:", df.shape)
print(df.head())

Shape before conversion: (18, 1)
                                   Data Description:
0                              RI : refractive index
1  Na: Sodium (unit measurement: weight percent i...
2                                      Mg: Magnesium
3                                       AI: Aluminum
4                                        Si: Silicon

In [12]:
for col in df.columns:
    try:
        df[col] = pd.to_numeric(df[col])
    except:
        pass

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Data Description:  17 non-null     object
dtypes: object(1)
memory usage: 276.0+ bytes

In [13]:
df = df.fillna(df.mean(numeric_only=True))

df.isna().sum()

Data Description:    1
dtype: int64

In [14]:

target_col = df.columns[-1]

X = df.drop(columns=[target_col])
y = df[target_col]

print("Dataset size:", df.shape)
print("Target classes:", y.unique())

Dataset size: (18, 1)
Target classes: ['RI : refractive index'
 'Na: Sodium (unit measurement: weight percent in corresponding oxide, as are attributes 4-10)'
 'Mg: Magnesium' 'AI: Aluminum' 'Si: Silicon' 'K:Potassium' 'Ca: Calcium'
 'Ba: Barium' 'Fe: Iron' nan 'Type: Type of glass: (class attribute)'
 '1 -- building_windows_float_processed'
 ' 2 --building_windows_non_float_processed'
 ' 3 --vehicle_windows_float_processed'
 ' 4 --vehicle_windows_non_float_processed (none in this database)'
 ' 5 --containers' ' 6 --tableware' ' 7 --headlamps']

In [17]:
X.shape

(18, 0)

In [18]:
import pandas as pd

xls = pd.ExcelFile("glass.xlsx")
print(xls.sheet_names)

['Description', 'glass']

In [19]:
df = pd.read_excel("glass.xlsx", sheet_name=0)
df.head()

  Prepare a model for glass classification using Random Forest
0                                  Data Description:
1                              RI : refractive index
2  Na: Sodium (unit measurement: weight percent i...
3                                      Mg: Magnesium
4                                       AI: Aluminum

In [20]:
print("Shape:", df.shape)
print("Columns:", df.columns)

Shape: (19, 1)
Columns: Index(['Prepare a model for glass classification using Random Forest'], dtype='object')

In [ ]:
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

In [ ]:
importances = pd.Series(model.feature_importances_, index=X.columns)

importances.sort_values().plot(kind="barh", figsize=(8,6))
plt.title("Feature Importance")
plt.show()